spring.application.name=For-Upc_backend

# Conexión a Supabase (Postgres) vía Session pooler
spring.datasource.url=jdbc:postgresql://aws-0-us-east-2.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.ypaaxwgfnadvbulfdbjn
spring.datasource.password=daniflow2026
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate crea/actualiza las tablas según tus @Entity
spring.jpa.hibernate.ddl-auto=update

# Si tenés schema.sql/data.sql y querés que se ejecuten igual
spring.sql.init.mode=always

# JWT
jwt.secret=8om3Tri283ZHDR5Mgtx1NK/+inkUpUEfZsmL0KQZAj8=

# URL de tu proyecto Supabase
supabase.url=https://ypaaxwgfnadvbulfdbjn.supabase.co

# Service Role Key de Supabase
supabase.service-key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlwYWF4d2dmbmFkdmJ1bGZkYmpuIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4ODk4NjgyNywiZXhwIjoyMTA0NTYyODI3fQ.PGNvbK5lnO7uUHjhbl4auHxovEFfmLgGy0rDume5t7E

# Nombre del bucket de Storage
supabase.storage.bucket=for-upc

# ==========================================
# ARCHIVOS MULTIPART
# ==========================================

# Tamaño máximo de un archivo individual
spring.servlet.multipart.max-file-size=10MB

# Tamaño máximo total de la petición
spring.servlet.multipart.max-request-size=15MB

logging.level.org.springframework.security=DEBUG