spring.application.name=For-Upc_backend
# Conexión a Supabase (Postgres) vía Session pooler
spring.datasource.url=jdbc:postgresql://aws-0-us-east-2.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.ypaaxwgfnadvbulfdbjn
spring.datasource.password=daniflow2026
spring.datasource.driver-class-name=org.postgresql.Driver
# Hibernate crea/actualiza las tablas según tus @Entity
spring.jpa.hibernate.ddl-auto=update
# Si tenés schema.sql/data.sql y querés que se ejecuten igual
spring.sql.init.mode=always

jwt.secret=clave-secreta-12345-abc
